services:
  - type: web
    name: editor-sample
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
